version: '3.8'

services:
  gptlite:
    build: app
    ports:
      - "3000:3000"
    environment:
      - OPENAI_API_BASE_URL=
      - OPENAI_API_KEY=
      - AZURE_OPENAI_API_BASE_URL=
      - AZURE_OPENAI_API_KEY=
      - AZURE_OPENAI_DEPLOYMENT=